name: 🔄 Ping Render Backend

on:
  # Запускаем по расписанию
  schedule:
    - cron: '*/5 * * * *'    # каждые 5 минут
  # И вручную из вкладки Actions
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping /docs endpoint
        run: |
          STATUS=$(curl -s -o /dev/null -w '%{http_code}' https://washing-platform.onrender.com/docs)
          echo "HTTP статус /docs: $STATUS"
          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Ошибка: сервер вернул $STATUS"
            exit 1
          fi
          echo "✅ Бэкенд жив (200 OK)"
